USE [PixelPalaceHotel]
GO

/****** Object:  Table [dbo].[Camere]    Script Date: 09/03/2024 12:55:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Camere](
	[IdCamera] [int] IDENTITY(1,1) NOT NULL,
	[NumeroCamera] [int] NOT NULL,
	[Descrizione] [nvarchar](50) NULL,
	[Tipologia] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_Camere] PRIMARY KEY CLUSTERED 
(
	[IdCamera] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Camere] UNIQUE NONCLUSTERED 
(
	[NumeroCamera] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

